### ISSUE TITLE
sorting function messes up result list

### ISSUE THREAD

**Issue by g00fy** [dcparker/jquery_plugins#11]
If for example you have a list of "ABC1", "ABC2", "ABC3". And the query you entered is "ABC", the results will be ordered 3 2 1 instead of 1 2 3 (I assume you give back 1 2 3).
This is because the indexOf('ABC') is always '0'.
This case is valid for the 'contains' algorithm.

I solved this by adding an option parameter "Don't sort".

**Comment by joshaven** [comment]
I have archived FuzzyString.  If FuzzyString is not meeting your needs then checkout https://github.com/joshaven/string_score 

Thank you for submitting an issue,
Joshaven
