### ISSUE TITLE
Ubearably slow performance of fuzzy-string

### ISSUE THREAD

**Issue by ikajaste** [dcparker/jquery_plugins#12]
I've tried using quickselect with `fuzzy-string.js` converting a `<select>` dropdown to a quickselect element. Everything works superb with few characters. However, when typing a longer string I encounter unbearably slow performance.

The performance keeps getting slower with each added character, until it reaches the point where the browser decides the script is stuck. This seems to be (depending on the environment of course) somewhere at 6-10 typed characters. I have tried this with two different computers, and on the latest Firefox, Chrome and IE. Tried using jQuery version 1.3.2 and 1.5 (latest).

My data in the form is actual data of about 100 organizations, with names ranging from 20 to 40 characters in UTF-8. I consider this a pretty regular (or even quite small) use case, considering the point of quickselect is to help user find the right option from a large selection.

Test demonstration of the problem: http://ilarikajaste.fi/dist/quickselect-problem/

**Comment by joshaven** [comment]
You may want to try this: https://github.com/joshaven/string_score
Sincerely,
Joshaven

**Comment by ikajaste** [comment]
Thanks, that woks very nicely!

(I'll keep the issue open, though, as it's still a significant problem with fuzzy-string.js)

**Comment by joshaven** [comment]
I will probably be archiving fuzzy-string and replacing it with string_score.  Thanks for the note.  I wrote string_score due to the very same issue.  Daniel will not be developing fuzzy-string any further.  I'll close the issue once I have taken care of this.  Thanks for the notice.

**Comment by joshaven** [comment]
I have documented this issue and recommended string_score  in the readme.

Thanks,
Joshaven
