### ISSUE TITLE
slowing and causing errors with simular matches 

### ISSUE THREAD

**Issue by joshaven** [dcparker/jquery_plugins#3]
If two options that are about 13 characters long are matching from the beginning but different at the end then the result takes a substantial amount of time... When the number of continuous matching characters approach 20 then the browser will ask you want to stop or continue waiting for the script.

Message from firefox:
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
Script: {path_to_js}/quicksilver.js:92

**Comment by dcparker** [comment]
This seems to be fixed in the next version.
