### ISSUE TITLE
Errors in the readme

### ISSUE THREAD

**Issue by darkdragon-001** [dcparker/jquery_plugins#5]
The quotes $(‘input#city_name_field’) --> ’ has to be replaced with normal quotes '.

Error in the Syntax (url has to be replaced with ajax): 
Wrong: $(‘input#city_name_field’).quickselect({url:‘/ajax/cities.json’});
Right: $(‘input#city_name_field’).quickselect({ajax:‘/ajax/cities.json’});

**Comment by dcparker** [comment]
Fixed, I hope.
