### ISSUE TITLE
IE7 CSS Div Results bug

### ISSUE THREAD

**Issue by dragonfly4** [dcparker/jquery_plugins#6]
First of all NICE WORK !!

The results DIV should be hidden on load of the page but in IE7 it is displayed. It goes away when you start typing. Doesn't happen in Google Chrome 4.0.249.89

Screenshots: http://img38.imageshack.us/g/fase3ieversion.jpg/

FYI: sample page doesn't load either, crashes since you try to load the plugin before the DOM is loaded so placing the javascript code at the bottom of the page solves that error

**Comment by dcparker** [comment]
Thanks. Can you please try the new updates? I don't know if it fixed it or not. If not, can you try to fix the IE7 hiding issue on your own, and submit the fix back to me?

**Comment by dragonfly4** [comment]
I will test it on monday with IE7, running IE8 here and looks good!

But one remark about your sample.html, all examples work except the Ajax Data. Does nothing in IE8 or in Google Chrome. Doesn't give any errors in the javascript console. Have you tested the sample with "zips_starting_with_49.json"

**Comment by dragonfly4** [comment]
old release: in IE7 + IE8 there appears a results div at the bottom, disappears when you start typing

new release: not fixed, tested in IE7 / IE8. Results div disappears when you start typing and results appear under textbox.
You submit value and then want to select 2nd value, then the results appear at the bottom of the page :(
Works fine in Google Chrome and Firefox but currently unusable in Internet Explorer. I would love to help you but I'll need some guidance as I'm not as good with Javascript as you are :)

Screenshots: http://img14.imageshack.us/g/ie804.jpg/

Any people here that have tested this with IE7/IE8 ?

thanks!

**Comment by dragonfly4** [comment]
well I couldn't get this working in all the browsers so I migrated my code to jQuery UI Autocomplete and now it's working fine. Thanks anyway for your help!!

**Comment by dragonfly4** [comment]
Closing my old tickets
